### ISSUE TITLE
Implement Cone of Influence reduction

### ISSUE THREAD

**Issue by ahmed-irfan** [upscale-project/pono#15]

**Comment by zhanghongce** [comment]
Hi, I have done something on this, basically a partial model generator based on COI.

https://github.com/zhanghongce/cosa2/blob/sygus-pdr/engines/sygus/partial_model.h
https://github.com/zhanghongce/cosa2/blob/sygus-pdr/engines/sygus/partial_model.cpp

**Comment by makaimann** [comment]
Thanks @zhanghongce ! Much appreciated. I think these are different, but your code could likely be useful soon as well.
