### ISSUE TITLE
MSAT related code in create_reducer_for is not guarded by macro

### ISSUE THREAD

**Issue by zhanghongce** [upscale-project/pono#204]
Hi I'm having compilation issues when not using MSAT. Therefore, I'm wondering: maybe this part of code needs to be guarded by macro `WITH_MSAT`? Thanks!

https://github.com/upscale-project/pono/blob/00c3017e19e373582dce96bddb34a60fa6ec84f4/smt/available_solvers.cpp#L158

**Comment by makaimann** [comment]
Oops, it was actually the `msat_env` and `msat_config` code. Fixed with 9f178ac79bfb476b0466b9a9cca0d77ee8a9cae4.
