### ISSUE TITLE
MBIC3 issue

### ISSUE THREAD

**Issue by zhanghongce** [upscale-project/pono#225]
Hi Makai, this is actually not related to anything I'm working on, maybe not an issue at all, but just to let you know currently MBIC3 seems to be abnormal: producing invariants that are checked to be not inductive.

You can try with the `anderson.2.prop1-func-interl.btor2` in the sample.

This is what I got on my end, by running: `pono -e mbic3 -v 3 --check-invar anderson.2.prop1-func-interl.btor2`

```
Propagation phase at frame 5
INVARCHECK: init |= inv...OK
INVARCHECK: inv & trans |= inv'...FAIL
INVARCHECK: inv |= prop...OK
Invariant Check FAILED
unknown
b0
```

**Comment by makaimann** [comment]
Thanks Hongce, I really appreciate it! This should fix it: https://github.com/upscale-project/pono/pull/226. I'll leave this issue open until that PR is merged. I'll also start a cluster run for `mbic3` (which I haven't been testing lately...).

**Comment by makaimann** [comment]
Fixed.

**Comment by makaimann** [comment]
![Screenshot from 2021-01-22 10-33-15](https://user-images.githubusercontent.com/23203473/105530900-59bb4c80-5c9d-11eb-98eb-aced095c319d.png)

No discrepancies after fix.
