### ISSUE TITLE
Look into performance issues with large unrolls

### ISSUE THREAD

**Issue by makaimann** [upscale-project/pono#29]
Cosa2 takes 4m to unroll to bound 26,000 on my desktop, and btormc takes only 9s to unroll and solve.

[example.tar.gz](https://github.com/upscale-project/cosa2/files/4463799/example.tar.gz)

**Comment by ahmed-irfan** [comment]
it get the following message when I try to reproduce
```
time ./cosa2  -k 26000 example/example.btor2 
Name has already been used.
unknown
b0

real	0m0.847s
user	0m0.438s
sys	0m0.409s

```

**Comment by makaimann** [comment]
Hmm that’s interesting. I was just using it through the API, not the command line. I’m not sure why that’d be any different though. I can look into it.

**Comment by makaimann** [comment]
Fixed in master -- that file reuses symbols for btor lines

**Comment by ahmed-irfan** [comment]
so, is there still the issue?

**Comment by makaimann** [comment]
Oh yeah, I didn’t look into the unroller at all. I’m not sure if it’s in cosa2 or smt-Switch btw

**Comment by ahmed-irfan** [comment]
if you have the test case, I would like to also look into it.

**Comment by makaimann** [comment]
Here's a test that just unrolls it -- takes about 4.5 minutes on my desktop. There's a Makefile that should work for you out of the box. Just needs to be in the top level of the cosa2 repository and have smt-switch already built in the usual place and cosa2 built.
[test-unroller.tar.gz](https://github.com/upscale-project/cosa2/files/4465392/test-unroller.tar.gz)

**Comment by lonsing** [comment]
Closing this, as the current version of Pono (https://github.com/upscale-project/pono/commit/d5f968dbffd9de21c347e15d74e4d54fea0c283d) solves the example in under 5s.
