### ISSUE TITLE
Using old version of smt-switch

### ISSUE THREAD

**Issue by cterrill26** [upscale-project/pono#315]
A recent bug fix was made in smt-switch: https://github.com/stanford-centaur/smt-switch/pull/321

The version of smt-switch installed by [contrib/setup-smt-switch.sh](https://github.com/upscale-project/pono/blob/master/contrib/setup-smt-switch.sh#L6) does not use this most recent version.

**Comment by makaimann** [comment]
Hey @cterrill26, thanks for the bug report on smt-switch and for following up. The install script was already updated with https://github.com/upscale-project/pono/commit/e2ee1c73cf8a909d7b5d3e6307e379b419105a07
